import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const AI_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'ai-e-01',
    themeId: 'ai',
    level: 'easy',
    prompt: 'O que significa "IA"?',
    options: [
      'Inteligência Aplicada',
      'Inteligência Artificial',
      'Informação Anônima',
      'Indexação Automática',
    ],
    correctIndex: 1,
    explanation: 'IA = Inteligência Artificial.',
    hint: 'A sigla brasileira é direta.',
  },
  {
    id: 'ai-e-02',
    themeId: 'ai',
    level: 'easy',
    prompt: 'O que é Machine Learning?',
    options: [
      'Programar regras manuais',
      'Modelos que aprendem padrões a partir de dados',
      'Compilação automática',
      'Banco de dados em memória',
    ],
    correctIndex: 1,
    explanation: 'ML treina modelos a partir de exemplos.',
    hint: 'O termo em inglês traz a palavra "aprendizado".',
  },
  {
    id: 'ai-e-03',
    themeId: 'ai',
    level: 'easy',
    prompt: 'Qual destes é um modelo supervisionado?',
    options: ['K-means', 'Random Forest', 'Apriori', 'DBSCAN'],
    correctIndex: 1,
    explanation: 'Random Forest exige rótulos; os demais são não-supervisionados.',
    hint: 'É o que precisa de rótulos para treinar.',
  },
  {
    id: 'ai-e-04',
    themeId: 'ai',
    level: 'easy',
    prompt: 'LLM significa:',
    options: [
      'Linear Logic Machine',
      'Large Language Model',
      'Low Latency Module',
      'Logic Layer Mapping',
    ],
    correctIndex: 1,
    explanation: 'LLM = grandes modelos de linguagem (GPT, Llama, etc.).',
    hint: 'A segunda palavra é "Language".',
  },
  {
    id: 'ai-e-05',
    themeId: 'ai',
    level: 'easy',
    prompt: '"Treinar" um modelo significa:',
    options: [
      'Compilar código',
      'Ajustar parâmetros para minimizar erro',
      'Apagar pesos',
      'Distribuir backups',
    ],
    correctIndex: 1,
    explanation: 'Treino otimiza pesos para reduzir a função de perda.',
    hint: 'Ajustar para errar menos.',
  },
  {
    id: 'ai-e-06',
    themeId: 'ai',
    level: 'easy',
    prompt: '"Inferência" em IA significa:',
    options: [
      'Treinamento do zero',
      'Usar modelo já treinado para fazer previsão',
      'Compactar pesos',
      'Buscar em base de dados',
    ],
    correctIndex: 1,
    explanation: 'Inferência é aplicar o modelo treinado a novas entradas.',
    hint: 'O modelo já treinado é "consultado".',
  },
  {
    id: 'ai-e-07',
    themeId: 'ai',
    level: 'easy',
    prompt: 'Qual destes é um framework de Deep Learning?',
    options: ['Pandas', 'PyTorch', 'NumPy', 'Matplotlib'],
    correctIndex: 1,
    explanation: 'PyTorch (e TensorFlow, JAX) são frameworks de Deep Learning.',
    hint: 'Começa com "Py" e termina com "Torch".',
  },
  {
    id: 'ai-e-08',
    themeId: 'ai',
    level: 'easy',
    prompt: 'Tokenização em NLP é:',
    options: [
      'Encriptar texto',
      'Dividir texto em unidades menores',
      'Traduzir idiomas',
      'Calcular sentimento',
    ],
    correctIndex: 1,
    explanation: 'Tokens podem ser palavras, sub-palavras, caracteres.',
    hint: 'É um passo de pré-processamento.',
  },
  {
    id: 'ai-e-09',
    themeId: 'ai',
    level: 'easy',
    prompt: 'Em ML, "overfitting" significa:',
    options: [
      'Modelo subajustado',
      'Memorizar dados de treino, mal generalizar',
      'Faltar dados',
      'Errar em todos',
    ],
    correctIndex: 1,
    explanation: 'Modelo decorou o treino e perde performance em dados novos.',
    hint: 'O "over" sugere "demais".',
  },
  {
    id: 'ai-e-10',
    themeId: 'ai',
    level: 'easy',
    prompt: 'Validação cruzada (cross-validation) serve para:',
    options: [
      'Cifrar treino',
      'Estimar performance com menor viés',
      'Acelerar inferência',
      'Selecionar GPU',
    ],
    correctIndex: 1,
    explanation: 'k-fold avalia o modelo em diferentes splits para reduzir variância da estimativa.',
    hint: 'Várias divisões do dataset.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'ai-m-01',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Embeddings de texto representam:',
    options: [
      'Apenas índices inteiros',
      'Vetores densos capturando significado',
      'Strings em ASCII',
      'Bytes brutos',
    ],
    correctIndex: 1,
    explanation: 'Embeddings mapeiam tokens/sentenças em vetores em R^n.',
    hint: 'São vetores no espaço contínuo.',
  },
  {
    id: 'ai-m-02',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Função de ativação não-linear comum em redes neurais:',
    options: ['Identidade', 'ReLU', 'Multiplicação', 'Identidade negativa'],
    correctIndex: 1,
    explanation: 'ReLU(x) = max(0, x) é amplamente usada.',
    hint: 'Sigla de três letras famosa.',
  },
  {
    id: 'ai-m-03',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Em transformers, "self-attention" calcula relação entre:',
    options: [
      'Camadas',
      'Tokens da mesma sequência',
      'Diferentes datasets',
      'Pesos do otimizador',
    ],
    correctIndex: 1,
    explanation: 'Atenção computa pesos relativos entre tokens da entrada.',
    hint: 'A atenção é "sobre si mesma".',
  },
  {
    id: 'ai-m-04',
    themeId: 'ai',
    level: 'medium',
    prompt: 'A função de perda em classificação multiclasse com softmax é tipicamente:',
    options: ['MSE', 'Cross-Entropy', 'Hinge', 'KL-Divergence isolada'],
    correctIndex: 1,
    explanation: 'Cross-Entropy combina-se naturalmente com softmax.',
    hint: 'Tem "entropy" no nome.',
  },
  {
    id: 'ai-m-05',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Em LLMs, "temperatura" controla:',
    options: [
      'Tamanho do contexto',
      'Aleatoriedade da amostragem',
      'Velocidade do GPU',
      'Tamanho do modelo',
    ],
    correctIndex: 1,
    explanation: 'Temperatura altera distribuição: maior = mais diversidade.',
    hint: 'Quanto maior, mais "criativo".',
  },
  {
    id: 'ai-m-06',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Regularização L2 (Ridge) penaliza:',
    options: [
      'Pesos absolutos',
      'Pesos ao quadrado (soma)',
      'Apenas viés',
      'Número de camadas',
    ],
    correctIndex: 1,
    explanation: 'L2 adiciona λ·Σwi² à função de perda.',
    hint: 'O número no nome dá uma pista.',
  },
  {
    id: 'ai-m-07',
    themeId: 'ai',
    level: 'medium',
    prompt: 'O que é RAG em LLMs?',
    options: [
      'Random Attention Gradient',
      'Retrieval-Augmented Generation',
      'Recursive Attention Graph',
      'Resource Allocation Group',
    ],
    correctIndex: 1,
    explanation: 'RAG enriquece prompts com recuperação de contexto externo.',
    hint: 'Combina busca + geração.',
  },
  {
    id: 'ai-m-08',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Hyperparâmetro em ML é:',
    options: [
      'Aprendido durante o treino',
      'Definido antes do treino (ex.: LR, profundidade)',
      'Sempre 1',
      'Saída do modelo',
    ],
    correctIndex: 1,
    explanation: 'Hiperparâmetros são configurações externas ao processo de otimização.',
    hint: 'Não é aprendido, é escolhido.',
  },
  {
    id: 'ai-m-09',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Em GANs, o "discriminador" tenta:',
    options: [
      'Gerar dados',
      'Diferenciar reais de gerados',
      'Otimizar GPU',
      'Reduzir dimensionalidade',
    ],
    correctIndex: 1,
    explanation: 'Discriminador classifica entre real e falso; gerador tenta enganá-lo.',
    hint: '"Discrimina" entre verdadeiro e falso.',
  },
  {
    id: 'ai-m-10',
    themeId: 'ai',
    level: 'medium',
    prompt: 'Em métricas de classificação, F1 é:',
    options: [
      'Média harmônica entre precisão e revocação',
      'Acurácia balanceada',
      'Sensibilidade pura',
      'Recall apenas',
    ],
    correctIndex: 0,
    explanation: 'F1 = 2·(P·R)/(P+R).',
    hint: 'Une precisão e recall em uma medida só.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'ai-h-01',
    themeId: 'ai',
    level: 'hard',
    prompt: 'Backpropagation usa que regra do cálculo?',
    options: ['Regra do produto', 'Regra da cadeia', 'Regra de L\'Hôpital', 'Regra da soma'],
    correctIndex: 1,
    explanation: 'Propagação reversa aplica a regra da cadeia para gradientes.',
    hint: 'É a regra que encadeia derivadas.',
  },
  {
    id: 'ai-h-02',
    themeId: 'ai',
    level: 'hard',
    prompt: 'O problema do "vanishing gradient" é comum em:',
    options: [
      'Redes muito rasas',
      'Redes profundas com saturação (ex.: sigmoid)',
      'Modelos lineares',
      'Apenas em GANs',
    ],
    correctIndex: 1,
    explanation: 'Ativações saturadas reduzem o sinal de gradiente em camadas iniciais.',
    hint: 'Ocorre quando o gradiente "desaparece" entre camadas.',
  },
  {
    id: 'ai-h-03',
    themeId: 'ai',
    level: 'hard',
    prompt: 'No paper "Attention is All You Need", o componente eliminado em relação a RNNs foi:',
    options: ['Embeddings', 'Recorrência', 'Softmax', 'Dropout'],
    correctIndex: 1,
    explanation: 'Transformer substitui recorrência por atenção, permitindo paralelismo.',
    hint: 'Substituída por atenção pura.',
  },
  {
    id: 'ai-h-04',
    themeId: 'ai',
    level: 'hard',
    prompt: 'Otimização Adam combina:',
    options: [
      'SGD com momentum + adaptação por parâmetro (tipo RMSProp)',
      'Apenas SGD',
      'Newton e quasi-Newton',
      'Coordinate descent',
    ],
    correctIndex: 0,
    explanation: 'Adam combina momento de primeira e segunda ordem por parâmetro.',
    hint: 'Une dois conceitos já vistos.',
  },
  {
    id: 'ai-h-05',
    themeId: 'ai',
    level: 'hard',
    prompt: 'Em RLHF, "RM" significa:',
    options: ['Recurrent Model', 'Reward Model', 'Random Mutation', 'Rate Manager'],
    correctIndex: 1,
    explanation: 'Reward Model prediz preferências humanas; usado como recompensa em RL.',
    hint: 'Aprende a "premiar" boas respostas.',
  },
  {
    id: 'ai-h-06',
    themeId: 'ai',
    level: 'hard',
    prompt: 'A complexidade do mecanismo de atenção em transformers é, em comprimento N:',
    options: ['O(1)', 'O(N)', 'O(N log N)', 'O(N²)'],
    correctIndex: 3,
    explanation: 'Atenção tradicional é quadrática em N.',
    hint: 'É quadrática.',
  },
  {
    id: 'ai-h-07',
    themeId: 'ai',
    level: 'hard',
    prompt: 'Quantização de modelos visa principalmente:',
    options: [
      'Aumentar precisão',
      'Reduzir memória/latência com perda controlada',
      'Eliminar overfitting',
      'Aumentar variância',
    ],
    correctIndex: 1,
    explanation: 'Representa pesos em menor precisão (int8/int4) para inferência eficiente.',
    hint: 'Pense em INT8/INT4.',
  },
  {
    id: 'ai-h-08',
    themeId: 'ai',
    level: 'hard',
    prompt: 'LoRA é uma técnica de:',
    options: [
      'Fine-tuning eficiente em parâmetros',
      'Treinamento total do modelo',
      'Inferência distribuída',
      'Coleta de dados',
    ],
    correctIndex: 0,
    explanation: 'Adapters de baixo posto reduzem parâmetros a treinar.',
    hint: '"Low-Rank Adaptation".',
  },
  {
    id: 'ai-h-09',
    themeId: 'ai',
    level: 'hard',
    prompt: 'Em "Mixture of Experts" (MoE), o roteador decide:',
    options: [
      'Quais especialistas processam cada token',
      'Quais GPUs alocar',
      'Quais dados eliminar',
      'Quais batch sizes usar',
    ],
    correctIndex: 0,
    explanation: 'O gating direciona tokens a subconjuntos de especialistas.',
    hint: 'Decide para qual "expert" mandar o token.',
  },
  {
    id: 'ai-h-10',
    themeId: 'ai',
    level: 'hard',
    prompt: 'Hallucination em LLMs refere-se a:',
    options: [
      'Erros visuais',
      'Geração de informação plausível porém incorreta',
      'Bug do compilador',
      'Falha de GPU',
    ],
    correctIndex: 1,
    explanation: 'Modelo produz conteúdo factualmente errado ou inventado.',
    hint: 'Plausível, mas falso.',
  },
] as const;
