import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const AUTH_TOKENS_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'auth-e-01',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'O que é autenticação?',
    options: [
      'Saber quem o usuário é',
      'Saber o que o usuário pode fazer',
      'Cifrar dados',
      'Comprimir arquivos',
    ],
    correctIndex: 0,
    explanation: 'Autenticação prova identidade; autorização decide permissões.',
    hint: 'Responde "quem você é?".',
  },
  {
    id: 'auth-e-02',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'JWT significa:',
    options: [
      'Java Web Token',
      'JSON Web Token',
      'JavaScript Web Toolkit',
      'Joint Web Type',
    ],
    correctIndex: 1,
    explanation: 'JWT = JSON Web Token (RFC 7519).',
    hint: 'O "J" vem de JSON.',
  },
  {
    id: 'auth-e-03',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'Cookie de sessão é geralmente:',
    options: [
      'Persistente para sempre',
      'Removido ao fechar o navegador',
      'Compartilhado entre origens',
      'Salvo no servidor',
    ],
    correctIndex: 1,
    explanation: 'Cookies de sessão expiram quando o navegador encerra (sem `Expires`/`Max-Age`).',
    hint: 'Tem vida curta, ligada à sessão.',
  },
  {
    id: 'auth-e-04',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'A função de hash deve ser:',
    options: [
      'Reversível',
      'Determinística',
      'Aleatória a cada chamada',
      'Lenta para validar',
    ],
    correctIndex: 1,
    explanation: 'Mesma entrada produz mesma saída; bom hash criptográfico não é reversível.',
    hint: 'Mesma entrada → mesma saída.',
  },
  {
    id: 'auth-e-05',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'Para senhas, devemos:',
    options: [
      'Armazenar em texto plano',
      'Cifrar reversível',
      'Hashear com algoritmo lento (bcrypt/argon2)',
      'Apenas em cookies',
    ],
    correctIndex: 2,
    explanation: 'Bcrypt/Argon2 incluem salt e custo, dificultando brute force.',
    hint: 'Lento é bom contra brute force.',
  },
  {
    id: 'auth-e-06',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'OAuth 2.0 serve para:',
    options: [
      'Cifrar mensagens',
      'Autorização delegada com tokens',
      'Logging',
      'Compressão',
    ],
    correctIndex: 1,
    explanation: 'OAuth permite que um app acesse recursos em nome do usuário.',
    hint: 'Pense em "Logar com Google".',
  },
  {
    id: 'auth-e-07',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'Em HTTP, o cabeçalho mais comum para JWT é:',
    options: ['Cookie', 'Authorization', 'Origin', 'Set-Cookie'],
    correctIndex: 1,
    explanation: '`Authorization: Bearer <token>`.',
    hint: 'Começa com "Bearer ".',
  },
  {
    id: 'auth-e-08',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'Salt em hash de senha serve para:',
    options: [
      'Reduzir tamanho',
      'Evitar rainbow tables',
      'Acelerar verificação',
      'Substituir senha',
    ],
    correctIndex: 1,
    explanation: 'Salt aleatório garante que hashes iguais para senhas iguais sejam diferentes entre usuários.',
    hint: 'Adiciona aleatoriedade por usuário.',
  },
  {
    id: 'auth-e-09',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'O que é 2FA?',
    options: [
      'Dois e-mails',
      'Dois fatores de autenticação',
      'Duas chaves SSH',
      'Dois servidores',
    ],
    correctIndex: 1,
    explanation: '2FA combina algo que você sabe + algo que você tem/é.',
    hint: 'O "FA" é "Factor Authentication".',
  },
  {
    id: 'auth-e-10',
    themeId: 'auth-tokens',
    level: 'easy',
    prompt: 'Em apps móveis, qual local é recomendado para guardar tokens?',
    options: [
      'AsyncStorage simples',
      'Console.log',
      'SecureStore / Keychain',
      'URL',
    ],
    correctIndex: 2,
    explanation: 'Armazenamento sensível: Keychain (iOS) / Keystore (Android).',
    hint: 'Pense em armazenamento criptografado.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'auth-m-01',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'Um JWT é composto por:',
    options: [
      'Header.Payload.Signature',
      'Apenas Payload',
      'Token.UUID',
      'Header.Body',
    ],
    correctIndex: 0,
    explanation: 'Três partes codificadas em Base64URL separadas por ponto.',
    hint: 'São três partes separadas por ponto.',
  },
  {
    id: 'auth-m-02',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'Em JWT, o claim `exp` significa:',
    options: ['Emissor', 'Expiração', 'Escopo', 'Algoritmo'],
    correctIndex: 1,
    explanation: '`exp` é o timestamp de expiração.',
    hint: 'Vem de "expiration".',
  },
  {
    id: 'auth-m-03',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'OAuth: qual fluxo é recomendado para SPA/mobile sem segredo?',
    options: [
      'Resource Owner Password Credentials',
      'Authorization Code com PKCE',
      'Implicit Flow (legado)',
      'Client Credentials',
    ],
    correctIndex: 1,
    explanation: 'PKCE protege apps públicos sem segredo de cliente.',
    hint: 'Tem a sigla PKCE no nome.',
  },
  {
    id: 'auth-m-04',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'CSRF é mitigado por:',
    options: [
      'CORS apenas',
      'SameSite cookies / CSRF token',
      'TLS apenas',
      'Hash bcrypt',
    ],
    correctIndex: 1,
    explanation: 'Cookies SameSite e CSRF tokens previnem requisições forjadas.',
    hint: 'Combina ajustes em cookies e tokens secundários.',
  },
  {
    id: 'auth-m-05',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'Em JWT, qual algoritmo é simétrico?',
    options: ['HS256', 'RS256', 'ES256', 'EdDSA'],
    correctIndex: 0,
    explanation: 'HMAC com SHA-256 usa segredo compartilhado.',
    hint: 'Começa por "H" de HMAC.',
  },
  {
    id: 'auth-m-06',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'Por que combinar access token + refresh token?',
    options: [
      'Performance pura',
      'Reduzir exposição: access curto, refresh longo guardado seguro',
      'Substituir senha',
      'Dobrar segurança do TLS',
    ],
    correctIndex: 1,
    explanation: 'Permite invalidar e renovar com janelas distintas.',
    hint: 'É sobre tempos de vida e exposição.',
  },
  {
    id: 'auth-m-07',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'O que é "rate limiting" em autenticação?',
    options: [
      'Velocidade de TLS',
      'Limitar tentativas para evitar brute force',
      'Compressão de respostas',
      'Cache no cliente',
    ],
    correctIndex: 1,
    explanation: 'Bloqueia ou desacelera tentativas excessivas (relacionado a A-06).',
    hint: 'Você está implementando algo parecido no app.',
  },
  {
    id: 'auth-m-08',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'O que é uma sessão "stateful" no servidor?',
    options: [
      'O servidor não guarda nada',
      'O servidor mantém estado por sessão (ex.: store)',
      'O cliente mantém estado',
      'Apenas via TLS',
    ],
    correctIndex: 1,
    explanation: 'Sessões stateful guardam dados no servidor; sessions IDs identificam.',
    hint: 'Tem estado guardado do lado servidor.',
  },
  {
    id: 'auth-m-09',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'OpenID Connect é construído sobre:',
    options: ['SAML', 'OAuth 2.0', 'Kerberos', 'LDAP'],
    correctIndex: 1,
    explanation: 'OIDC adiciona camada de identidade ao OAuth 2.',
    hint: 'É uma extensão de um padrão de autorização.',
  },
  {
    id: 'auth-m-10',
    themeId: 'auth-tokens',
    level: 'medium',
    prompt: 'Boa prática: token JWT deve ser:',
    options: [
      'Persistente para sempre',
      'Curto e renovável',
      'Igual a senha do usuário',
      'Em texto plano em URL',
    ],
    correctIndex: 1,
    explanation: 'Tokens curtos + refresh = compromisso seguro.',
    hint: 'Tempo de vida curto reduz risco.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'auth-h-01',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'Algoritmo "none" em JWT (alg: none) é:',
    options: [
      'Recomendado',
      'Vulnerabilidade comum se aceito',
      'Padrão',
      'Equivalente a HS256',
    ],
    correctIndex: 1,
    explanation: 'Aceitar `none` permite forjar tokens sem assinatura.',
    hint: 'Erro famoso em libraries antigas.',
  },
  {
    id: 'auth-h-02',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'No fluxo "refresh token rotation":',
    options: [
      'O refresh nunca muda',
      'Cada uso emite novo refresh, invalidando o anterior',
      'Tokens são reciclados em loop',
      'Não usa refresh tokens',
    ],
    correctIndex: 1,
    explanation: 'Rotação detecta abuso por reutilização de refresh.',
    hint: 'Cada renovação invalida o token anterior.',
  },
  {
    id: 'auth-h-03',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'OAuth state parameter previne:',
    options: ['Phishing', 'CSRF no callback', 'Replay TLS', 'Brute force'],
    correctIndex: 1,
    explanation: 'O `state` deve ser opaco/único e validado para garantir que a resposta veio da requisição correta.',
    hint: 'Mitiga um ataque comum no callback.',
  },
  {
    id: 'auth-h-04',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'Diferença chave entre Argon2id e bcrypt:',
    options: [
      'Não há diferença real',
      'Argon2id resiste a GPU/ASIC com parâmetros de memória',
      'Bcrypt é assimétrico',
      'Argon2id é mais fraco',
    ],
    correctIndex: 1,
    explanation: 'Argon2id ganhou o PHC; combina resistência a ataques side-channel e GPU.',
    hint: 'Argon2id explora consumo de memória.',
  },
  {
    id: 'auth-h-05',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'Em mTLS, autenticação ocorre:',
    options: [
      'Apenas servidor identifica o cliente',
      'Cliente e servidor autenticam-se mutuamente via certificados',
      'Apenas cliente autentica via senha',
      'Sem TLS',
    ],
    correctIndex: 1,
    explanation: 'mTLS exige certificado do cliente para autenticação mútua.',
    hint: 'O "m" significa "mutual".',
  },
  {
    id: 'auth-h-06',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'JWT armazenado em localStorage é vulnerável principalmente a:',
    options: ['CSRF', 'XSS', 'Replay TLS', 'Race conditions'],
    correctIndex: 1,
    explanation: 'localStorage é lido por JS; XSS rouba o token.',
    hint: 'Qualquer script da página tem acesso.',
  },
  {
    id: 'auth-h-07',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'Atributo `Secure` em cookies garante:',
    options: [
      'Apenas envio em HTTPS',
      'Não acessível por JS',
      'SameSite Strict',
      'Persistência infinita',
    ],
    correctIndex: 0,
    explanation: '`Secure` evita envio em conexões não criptografadas.',
    hint: 'Trata-se de canal seguro.',
  },
  {
    id: 'auth-h-08',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'Em "Token-binding", o objetivo principal é:',
    options: [
      'Vincular tokens a uma conexão TLS específica',
      'Cifrar tokens com base64',
      'Acelerar o login',
      'Eliminar refresh tokens',
    ],
    correctIndex: 0,
    explanation: 'Token-binding amarra o token a uma chave de sessão TLS, mitigando roubo.',
    hint: 'Liga o token à conexão segura.',
  },
  {
    id: 'auth-h-09',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'PASETO foi proposto como alternativa a:',
    options: ['JWT (com algoritmos seguros por padrão)', 'OAuth2', 'mTLS', 'OIDC'],
    correctIndex: 0,
    explanation: 'PASETO elimina escolhas inseguras com versões fixas de algoritmos.',
    hint: 'O nome lembra "Platform-Agnostic SEcurity TOkens".',
  },
  {
    id: 'auth-h-10',
    themeId: 'auth-tokens',
    level: 'hard',
    prompt: 'DPoP (Demonstrating Proof of Possession) serve para:',
    options: [
      'Provar posse do token via assinatura por requisição',
      'Cifrar payload do JWT',
      'Subir tokens via WebSocket',
      'Substituir refresh tokens',
    ],
    correctIndex: 0,
    explanation: 'DPoP exige que o cliente prove posse da chave em cada requisição.',
    hint: '"Proof of Possession" está no nome.',
  },
] as const;
