import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const DATABASES_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'db-e-01',
    themeId: 'databases',
    level: 'easy',
    prompt: 'O que significa SQL?',
    options: [
      'Simple Question Language',
      'Structured Query Language',
      'Standard Query Layer',
      'Server Query Logic',
    ],
    correctIndex: 1,
    explanation: 'SQL = Structured Query Language.',
    hint: 'A primeira palavra é "Structured".',
  },
  {
    id: 'db-e-02',
    themeId: 'databases',
    level: 'easy',
    prompt: 'Qual comando SQL recupera dados?',
    options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'],
    correctIndex: 2,
    explanation: 'SELECT é usado para consultas.',
    hint: 'É o comando de leitura.',
  },
  {
    id: 'db-e-03',
    themeId: 'databases',
    level: 'easy',
    prompt: 'PRIMARY KEY garante:',
    options: [
      'Apenas indexação',
      'Unicidade e não-nulo',
      'Apenas tipo numérico',
      'Apenas chave externa',
    ],
    correctIndex: 1,
    explanation: 'Chave primária é única e não nula.',
    hint: 'Ela identifica o registro.',
  },
  {
    id: 'db-e-04',
    themeId: 'databases',
    level: 'easy',
    prompt: 'Em SQL, JOIN serve para:',
    options: [
      'Excluir registros',
      'Combinar linhas de duas ou mais tabelas',
      'Renomear coluna',
      'Criar tabela',
    ],
    correctIndex: 1,
    explanation: 'JOIN une tabelas por condição (ON ...).',
    hint: 'O nome em inglês significa "juntar".',
  },
  {
    id: 'db-e-05',
    themeId: 'databases',
    level: 'easy',
    prompt: 'NoSQL não é sinônimo de:',
    options: [
      'Sem SQL nenhum',
      'Não relacional',
      'Esquema flexível',
      'Modelo diferente do relacional',
    ],
    correctIndex: 0,
    explanation: 'NoSQL = "Not Only SQL"; muitos suportam linguagens semelhantes a SQL.',
    hint: 'O acrônimo significa "Not Only SQL".',
  },
  {
    id: 'db-e-06',
    themeId: 'databases',
    level: 'easy',
    prompt: 'Qual destes é um banco NoSQL orientado a documentos?',
    options: ['Postgres', 'MySQL', 'MongoDB', 'SQLite'],
    correctIndex: 2,
    explanation: 'MongoDB armazena documentos BSON/JSON.',
    hint: 'Famoso pelo "M" do MEAN stack.',
  },
  {
    id: 'db-e-07',
    themeId: 'databases',
    level: 'easy',
    prompt: 'Em SQL, DELETE remove:',
    options: [
      'A tabela inteira',
      'Linhas selecionadas',
      'Coluna específica',
      'Banco inteiro',
    ],
    correctIndex: 1,
    explanation: 'DELETE remove linhas; DROP remove a tabela.',
    hint: 'É o oposto de INSERT.',
  },
  {
    id: 'db-e-08',
    themeId: 'databases',
    level: 'easy',
    prompt: 'WHERE em SQL serve para:',
    options: [
      'Ordenar resultados',
      'Filtrar linhas',
      'Agrupar colunas',
      'Renomear tabela',
    ],
    correctIndex: 1,
    explanation: 'WHERE define condição de filtragem.',
    hint: 'É a cláusula de filtro.',
  },
  {
    id: 'db-e-09',
    themeId: 'databases',
    level: 'easy',
    prompt: 'Qual destes é um modelo de banco de dados?',
    options: ['Relacional', 'Hexagonal', 'Tipográfico', 'Vetorial puro'],
    correctIndex: 0,
    explanation: 'Relacional é o modelo clássico (Codd, 1970).',
    hint: 'Modelo que usa tabelas com chaves.',
  },
  {
    id: 'db-e-10',
    themeId: 'databases',
    level: 'easy',
    prompt: 'Coluna do tipo VARCHAR armazena:',
    options: ['Inteiros', 'Texto de tamanho variável', 'Data', 'Booleano'],
    correctIndex: 1,
    explanation: 'VARCHAR(n) é cadeia de caracteres até n.',
    hint: 'É de texto, mas não fixo.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'db-m-01',
    themeId: 'databases',
    level: 'medium',
    prompt: 'ACID — qual NÃO faz parte?',
    options: ['Atomicidade', 'Consistência', 'Identidade', 'Durabilidade'],
    correctIndex: 2,
    explanation: 'ACID = Atomicidade, Consistência, Isolamento, Durabilidade.',
    hint: 'Falta o "I" correto.',
  },
  {
    id: 'db-m-02',
    themeId: 'databases',
    level: 'medium',
    prompt: 'O que GROUP BY faz?',
    options: [
      'Filtra após agregar',
      'Junta tabelas',
      'Agrupa linhas para funções de agregação',
      'Ordena resultados',
    ],
    correctIndex: 2,
    explanation: 'GROUP BY agrupa linhas pelo valor das colunas, permitindo COUNT, SUM, etc.',
    hint: 'O nome diz "agrupar".',
  },
  {
    id: 'db-m-03',
    themeId: 'databases',
    level: 'medium',
    prompt: 'INNER JOIN retorna:',
    options: [
      'Linhas mesmo sem correspondência',
      'Apenas linhas com correspondência em ambos os lados',
      'Apenas linhas da esquerda',
      'Apenas linhas da direita',
    ],
    correctIndex: 1,
    explanation: 'INNER mantém apenas pares que satisfazem a condição.',
    hint: 'Há também LEFT/RIGHT/FULL para outros casos.',
  },
  {
    id: 'db-m-04',
    themeId: 'databases',
    level: 'medium',
    prompt: 'Índice em coluna ajuda principalmente em:',
    options: [
      'Inserções massivas',
      'Buscas e ordenações por essa coluna',
      'Reduzir tamanho do banco',
      'Cifrar dados',
    ],
    correctIndex: 1,
    explanation: 'Índices aceleram leituras; podem custar em escrita.',
    hint: 'Pense numa "agenda" para encontrar rápido.',
  },
  {
    id: 'db-m-05',
    themeId: 'databases',
    level: 'medium',
    prompt: 'Normalização visa principalmente:',
    options: [
      'Acelerar SELECTs',
      'Reduzir redundância e anomalias',
      'Diminuir índices',
      'Substituir backup',
    ],
    correctIndex: 1,
    explanation: 'Formas normais reduzem duplicação e dependências indesejadas.',
    hint: 'Trata-se de organização lógica dos dados.',
  },
  {
    id: 'db-m-06',
    themeId: 'databases',
    level: 'medium',
    prompt: 'Em transações, "rollback" significa:',
    options: [
      'Repetir transação',
      'Desfazer alterações desde o início',
      'Salvar parcial',
      'Fechar conexão',
    ],
    correctIndex: 1,
    explanation: 'Rollback retorna ao estado anterior ao BEGIN.',
    hint: 'O oposto de commit.',
  },
  {
    id: 'db-m-07',
    themeId: 'databases',
    level: 'medium',
    prompt: 'O que faz LIMIT em SQL?',
    options: [
      'Define tamanho do banco',
      'Restringe número de linhas retornadas',
      'Filtra colunas',
      'Indexa tabela',
    ],
    correctIndex: 1,
    explanation: 'LIMIT n retorna no máximo n linhas.',
    hint: 'É comum com OFFSET para paginação.',
  },
  {
    id: 'db-m-08',
    themeId: 'databases',
    level: 'medium',
    prompt: 'Em NoSQL chave-valor, exemplo é:',
    options: ['Postgres', 'Redis', 'Neo4j', 'Cassandra'],
    correctIndex: 1,
    explanation: 'Redis é key-value store em memória.',
    hint: 'Banco comum como cache.',
  },
  {
    id: 'db-m-09',
    themeId: 'databases',
    level: 'medium',
    prompt: 'O que é uma "view" em SQL?',
    options: [
      'Tabela física duplicada',
      'Consulta nomeada que se comporta como tabela virtual',
      'Backup',
      'Tipo de índice',
    ],
    correctIndex: 1,
    explanation: 'Views encapsulam consultas, oferecendo uma "tabela" derivada.',
    hint: 'É uma "tabela virtual" baseada em uma query.',
  },
  {
    id: 'db-m-10',
    themeId: 'databases',
    level: 'medium',
    prompt: 'CONSTRAINT FOREIGN KEY garante:',
    options: [
      'Unicidade na própria tabela',
      'Integridade referencial entre tabelas',
      'Tipo correto da coluna',
      'Indexação automática única',
    ],
    correctIndex: 1,
    explanation: 'Foreign key liga uma coluna à PK de outra tabela.',
    hint: 'Refere-se a outra tabela.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'db-h-01',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Em teoria CAP, sob partição, deve-se escolher entre:',
    options: [
      'Consistência e Disponibilidade',
      'Consistência e Performance',
      'Durabilidade e Atomicidade',
      'Sharding e Replication',
    ],
    correctIndex: 0,
    explanation: 'CAP: na presença de partição (P), escolhe-se entre C e A.',
    hint: 'É a dicotomia clássica do "CAP".',
  },
  {
    id: 'db-h-02',
    themeId: 'databases',
    level: 'hard',
    prompt: 'O que é "deadlock" em banco de dados?',
    options: [
      'Quando o banco fica offline',
      'Duas transações esperam recursos uma da outra',
      'Falha de disco',
      'Erro de sintaxe',
    ],
    correctIndex: 1,
    explanation: 'Ciclo de espera entre transações com locks.',
    hint: 'Pense em duas threads se esperando mutuamente.',
  },
  {
    id: 'db-h-03',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Em nível de isolamento "Read Committed", podem ocorrer:',
    options: [
      'Dirty reads',
      'Phantom reads e non-repeatable reads',
      'Apenas serializable conflicts',
      'Nenhuma anomalia',
    ],
    correctIndex: 1,
    explanation: 'Read Committed evita dirty reads, mas permite non-repeatable reads e phantoms.',
    hint: 'Evita o sujeito, mas permite o repetível e o fantasma.',
  },
  {
    id: 'db-h-04',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Sharding é técnica de:',
    options: [
      'Backup criptografado',
      'Particionamento horizontal por hash/intervalo',
      'Replica master-slave',
      'Compressão de índices',
    ],
    correctIndex: 1,
    explanation: 'Distribui dados em "shards" entre nós para escalar horizontalmente.',
    hint: 'Tem a ver com "fragmentar".',
  },
  {
    id: 'db-h-05',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Índice tipo "covering" significa:',
    options: [
      'Cobre todas as tabelas',
      'Contém todas as colunas da consulta, evitando hit na tabela',
      'Index exclusivo',
      'Bloqueio total',
    ],
    correctIndex: 1,
    explanation: 'Quando o índice "cobre" a query, o engine evita acessar a tabela base.',
    hint: 'Tem a ver com evitar acesso à tabela principal.',
  },
  {
    id: 'db-h-06',
    themeId: 'databases',
    level: 'hard',
    prompt: 'EXPLAIN/EXPLAIN ANALYZE retorna:',
    options: [
      'O dado retornado',
      'O plano de execução da consulta',
      'Estatísticas do servidor',
      'Backup parcial',
    ],
    correctIndex: 1,
    explanation: 'Mostra como o otimizador pretende (ou executou) a consulta.',
    hint: 'Útil para otimização.',
  },
  {
    id: 'db-h-07',
    themeId: 'databases',
    level: 'hard',
    prompt: 'MVCC em bancos como Postgres permite:',
    options: [
      'Leituras sem bloquear escritas e vice-versa',
      'Substituir ACID',
      'Eliminar transações',
      'Evitar backup',
    ],
    correctIndex: 0,
    explanation: 'Multi-Version Concurrency Control mantém versões dos dados para concorrência.',
    hint: 'A palavra-chave é "versões".',
  },
  {
    id: 'db-h-08',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Em modelagem relacional, dependência funcional X → Y diz que:',
    options: [
      'Y determina X',
      'X determina Y',
      'X e Y são independentes',
      'X é chave primária',
    ],
    correctIndex: 1,
    explanation: 'Para cada valor de X há exatamente um Y associado.',
    hint: 'A seta indica "determina".',
  },
  {
    id: 'db-h-09',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Em SQL, "window functions" (ex.: ROW_NUMBER()) operam sobre:',
    options: [
      'A tabela toda sem partição',
      'Conjuntos de linhas definidos por OVER(PARTITION BY ...)',
      'Apenas índices',
      'Snapshots',
    ],
    correctIndex: 1,
    explanation: 'Window functions operam em partições e ordens definidas pelo OVER().',
    hint: 'OVER(PARTITION BY ...) define o escopo.',
  },
  {
    id: 'db-h-10',
    themeId: 'databases',
    level: 'hard',
    prompt: 'Em bancos colunares (ex.: ClickHouse), benefícios principais são:',
    options: [
      'Inserções em massa lentas',
      'Compressão eficiente e leitura por coluna em analytics',
      'Apenas para OLTP',
      'Eliminação de índices',
    ],
    correctIndex: 1,
    explanation: 'Armazenamento por colunas favorece OLAP, compressão e varreduras parciais.',
    hint: 'Pense em workloads analíticos.',
  },
] as const;
