import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const DATA_STRUCTURES_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'ds-e-01',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Qual estrutura segue a regra FIFO?',
    options: ['Pilha', 'Fila', 'Árvore', 'Grafo'],
    correctIndex: 1,
    explanation: 'FIFO = First-In, First-Out, ou seja, fila.',
    hint: 'A sigla é "First-In, First-Out".',
  },
  {
    id: 'ds-e-02',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Qual estrutura segue a regra LIFO?',
    options: ['Pilha', 'Fila', 'Lista', 'Heap'],
    correctIndex: 0,
    explanation: 'LIFO = Last-In, First-Out (pilha).',
    hint: 'O último a entrar é o primeiro a sair.',
  },
  {
    id: 'ds-e-03',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Qual estrutura armazena elementos com chave e valor?',
    options: ['Array', 'Lista', 'Hash Map', 'Pilha'],
    correctIndex: 2,
    explanation: 'Hash maps (dicionários) mapeiam chaves a valores.',
    hint: 'Pense em "dicionário".',
  },
  {
    id: 'ds-e-04',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Em uma árvore binária cada nó tem no máximo quantos filhos?',
    options: ['1', '2', '3', 'qualquer'],
    correctIndex: 1,
    explanation: 'Binária = no máximo 2 filhos por nó.',
    hint: 'O nome já dá a dica.',
  },
  {
    id: 'ds-e-05',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Acesso por índice em arrays é, em média:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctIndex: 0,
    explanation: 'Cálculo direto de endereço.',
    hint: 'Endereço é calculado, não percorrido.',
  },
  {
    id: 'ds-e-06',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Em uma lista ligada simples, cada nó aponta para:',
    options: ['O anterior', 'O próximo', 'Ambos', 'Nenhum'],
    correctIndex: 1,
    explanation: 'Lista simples aponta apenas para o próximo.',
    hint: 'Simples = um caminho.',
  },
  {
    id: 'ds-e-07',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Em uma pilha, a operação que remove o topo chama-se:',
    options: ['push', 'pop', 'peek', 'enqueue'],
    correctIndex: 1,
    explanation: 'push adiciona, pop remove o topo.',
    hint: 'Em inglês significa "estourar".',
  },
  {
    id: 'ds-e-08',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Heap é tipicamente usado para implementar:',
    options: ['Fila de prioridade', 'Set ordenado', 'Stack', 'Hash table'],
    correctIndex: 0,
    explanation: 'Min/max-heap acessa o maior/menor em O(log n).',
    hint: 'Pense em filas onde alguns "passam na frente".',
  },
  {
    id: 'ds-e-09',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Um array em C tem tamanho:',
    options: ['Dinâmico em tempo de execução', 'Fixo', 'Crescente apenas', 'Indeterminado'],
    correctIndex: 1,
    explanation: 'Arrays em C têm tamanho fixo na compilação (sem realloc/heap).',
    hint: 'Em C clássico não cresce sozinho.',
  },
  {
    id: 'ds-e-10',
    themeId: 'data-structures',
    level: 'easy',
    prompt: 'Conjuntos (Sets) não permitem:',
    options: ['Duplicatas', 'Strings', 'Inserção', 'Ordenação'],
    correctIndex: 0,
    explanation: 'A definição de conjunto exclui elementos repetidos.',
    hint: 'Cada elemento aparece no máximo uma vez.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'ds-m-01',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Inserção no início de uma lista ligada é:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    correctIndex: 0,
    explanation: 'Basta atualizar o ponteiro head.',
    hint: 'Não precisa percorrer todo mundo.',
  },
  {
    id: 'ds-m-02',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Busca em árvore binária de busca balanceada:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctIndex: 1,
    explanation: 'Em BBSTs (AVL, Red-Black) a altura é O(log n).',
    hint: 'Cortando pela metade a cada nível.',
  },
  {
    id: 'ds-m-03',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Qual estrutura usa hashing para garantir busca média O(1)?',
    options: ['BST', 'Heap', 'Hash Table', 'Trie'],
    correctIndex: 2,
    explanation: 'Hash table com função de hash adequada e baixa colisão.',
    hint: 'O próprio nome contém "Hash".',
  },
  {
    id: 'ds-m-04',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Qual a diferença entre lista ligada simples e duplamente ligada?',
    options: [
      'Não há diferença prática',
      'A duplamente também referencia o nó anterior',
      'Lista simples é circular',
      'Apenas as listas duplas têm head',
    ],
    correctIndex: 1,
    explanation: 'Listas duplamente ligadas têm ponteiros para anterior e próximo.',
    hint: '"Duplamente" sugere dois sentidos.',
  },
  {
    id: 'ds-m-05',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Trie é usada principalmente para:',
    options: [
      'Ordenar inteiros',
      'Armazenar e buscar strings/prefixos',
      'Calcular grafos',
      'Algoritmos numéricos',
    ],
    correctIndex: 1,
    explanation: 'Estrutura especializada em busca por prefixo.',
    hint: 'Comum em autocomplete.',
  },
  {
    id: 'ds-m-06',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Em uma fila circular, quando "wrap-around" ocorre?',
    options: [
      'Quando se atinge o final do array e volta ao início',
      'Quando há overflow',
      'Quando o ponteiro fica nulo',
      'Quando há um loop infinito',
    ],
    correctIndex: 0,
    explanation: 'Após o último índice, retorna ao 0 para reutilizar espaço.',
    hint: 'O nome "circular" já indica.',
  },
  {
    id: 'ds-m-07',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Heap binário máximo: qual o pai em índice i (base 0)?',
    options: ['i/2', '(i-1)/2', '2i', '2i+1'],
    correctIndex: 1,
    explanation: 'Em base 0, pai é (i-1)/2; filhos 2i+1 e 2i+2.',
    hint: 'A base é 0, considere o ajuste.',
  },
  {
    id: 'ds-m-08',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Vantagem de uma BST balanceada sobre array ordenado:',
    options: [
      'Acesso por índice constante',
      'Inserção/remoção O(log n) mantendo ordem',
      'Menor memória',
      'Iteração mais simples',
    ],
    correctIndex: 1,
    explanation: 'BSTs balanceadas mantêm ordem com inserção e remoção logarítmicas.',
    hint: 'Pense em alterar a coleção, não só buscar.',
  },
  {
    id: 'ds-m-09',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Hash table — qual a abordagem para tratar colisões?',
    options: [
      'Apenas redimensionar',
      'Chaining ou open addressing',
      'Ignorar',
      'Substituir a chave',
    ],
    correctIndex: 1,
    explanation: 'Chaining (lista nos buckets) ou open addressing (probing).',
    hint: 'Há duas estratégias clássicas.',
  },
  {
    id: 'ds-m-10',
    themeId: 'data-structures',
    level: 'medium',
    prompt: 'Em árvores AVL, fator de balanceamento de um nó é:',
    options: [
      'Altura à esquerda',
      'Altura à direita',
      'Altura(esq) - Altura(dir)',
      'Soma dos filhos',
    ],
    correctIndex: 2,
    explanation: 'Diferença entre as alturas das subárvores; mantido em {-1, 0, +1}.',
    hint: 'É uma diferença de alturas.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'ds-h-01',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Red-Black Tree garante altura proporcional a:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(√n)'],
    correctIndex: 1,
    explanation: 'Propriedades vermelhas/pretas limitam a altura a 2·log(n+1).',
    hint: 'Está entre as estruturas balanceadas.',
  },
  {
    id: 'ds-h-02',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Estrutura de dados ideal para "menor elemento de um intervalo" (RMQ) com pré-processamento:',
    options: ['Heap', 'Sparse Table', 'Trie', 'Fila circular'],
    correctIndex: 1,
    explanation: 'Sparse Table responde RMQ idempotente em O(1) após O(n log n) de pré-processamento.',
    hint: 'A pré-computação é O(n log n).',
  },
  {
    id: 'ds-h-03',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Union-Find com path compression e union by rank tem complexidade amortizada de:',
    options: ['O(1)', 'O(log n)', 'O(α(n))', 'O(n)'],
    correctIndex: 2,
    explanation: 'A inversa de Ackermann α(n) é praticamente constante na prática.',
    hint: 'A complexidade envolve inversa de uma função famosa.',
  },
  {
    id: 'ds-h-04',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'B-Tree é particularmente usada em:',
    options: [
      'Memória cache da CPU',
      'Índices de bancos de dados e sistemas de arquivos',
      'Hashes criptográficos',
      'Bancos em memória RAM apenas',
    ],
    correctIndex: 1,
    explanation: 'B-Trees minimizam acessos a disco mantendo a árvore "larga".',
    hint: 'Pense em armazenamento em disco.',
  },
  {
    id: 'ds-h-05',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Skip list é um substituto probabilístico de qual estrutura?',
    options: ['Hash table', 'BST balanceada', 'Heap', 'Trie'],
    correctIndex: 1,
    explanation: 'Skip lists oferecem busca/inserção O(log n) esperado, similar a BSTs.',
    hint: 'É baseada em listas com "atalhos" e desempenho logarítmico.',
  },
  {
    id: 'ds-h-06',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Em árvores binárias, percurso "in-order" sobre uma BST produz:',
    options: [
      'Ordem aleatória',
      'Ordem reversa',
      'Ordem crescente das chaves',
      'Pré-fixos',
    ],
    correctIndex: 2,
    explanation: 'In-order percorre esquerda → raiz → direita, ordenando a sequência.',
    hint: 'É o percurso que respeita a propriedade da BST.',
  },
  {
    id: 'ds-h-07',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Qual estrutura permite "k-ésimo menor" elemento eficientemente em alterações?',
    options: ['Array simples', 'Árvore de Fenwick (BIT)', 'Fila', 'Hash Set'],
    correctIndex: 1,
    explanation: 'BIT/Segment Tree resolvem k-ésima estatística em O(log n).',
    hint: 'É uma árvore comum em problemas de prefixos.',
  },
  {
    id: 'ds-h-08',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Hash perfeita serve para:',
    options: [
      'Garantir zero colisões em conjunto estático',
      'Eliminar a função de hash',
      'Acelerar inserção dinâmica',
      'Substituir Bloom filters',
    ],
    correctIndex: 0,
    explanation: 'É construída sobre um conjunto fixo de chaves; nenhuma colisão.',
    hint: 'A palavra "perfeita" sugere ausência de algo.',
  },
  {
    id: 'ds-h-09',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Bloom Filter pode resultar em:',
    options: [
      'Falsos positivos',
      'Falsos negativos',
      'Ambos com igual probabilidade',
      'Nenhum',
    ],
    correctIndex: 0,
    explanation: 'Pode dizer "talvez presente" (falso positivo), nunca falso negativo.',
    hint: 'Pode acusar erradamente "está presente".',
  },
  {
    id: 'ds-h-10',
    themeId: 'data-structures',
    level: 'hard',
    prompt: 'Em segment tree com lazy propagation, atualizações de intervalo são:',
    options: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'],
    correctIndex: 0,
    explanation: 'Propagação preguiçosa adia atualizações, mantendo O(log n) por operação.',
    hint: 'Pense em altura da árvore segmentada.',
  },
] as const;
