import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const LANGUAGES_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'lng-e-01',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Qual destes é um tipo primitivo em JavaScript?',
    options: ['Array', 'string', 'Map', 'Set'],
    correctIndex: 1,
    explanation: 'string, number, boolean, null, undefined, symbol e bigint são primitivos. Array, Map e Set são objetos.',
    hint: 'Pense no que armazena apenas um valor, não uma coleção.',
  },
  {
    id: 'lng-e-02',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Em Python, qual a extensão usual de arquivos-fonte?',
    options: ['.pyt', '.py', '.python', '.pt'],
    correctIndex: 1,
    explanation: 'Arquivos Python têm extensão .py.',
    hint: 'É a extensão curta com duas letras.',
  },
  {
    id: 'lng-e-03',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Qual palavra-chave declara uma variável imutável em JavaScript (ES6+)?',
    options: ['var', 'let', 'const', 'static'],
    correctIndex: 2,
    explanation: '`const` declara uma referência que não pode ser reatribuída.',
    hint: 'O nome lembra "constante".',
  },
  {
    id: 'lng-e-04',
    themeId: 'languages',
    level: 'easy',
    prompt: 'TypeScript é uma linguagem que…',
    options: [
      'Substitui o navegador',
      'Adiciona tipagem estática ao JavaScript',
      'É compilada para bytecode Java',
      'Só funciona em servidores',
    ],
    correctIndex: 1,
    explanation: 'TypeScript adiciona tipos estáticos ao JavaScript e transpila para JS.',
    hint: 'O próprio nome dá uma dica.',
  },
  {
    id: 'lng-e-05',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Em Java, qual o tipo usado para texto?',
    options: ['char', 'String', 'text', 'str'],
    correctIndex: 1,
    explanation: 'String em Java representa cadeias de caracteres imutáveis.',
    hint: 'Em Java esse tipo começa com letra maiúscula.',
  },
  {
    id: 'lng-e-06',
    themeId: 'languages',
    level: 'easy',
    prompt: 'O que significa a sigla HTML?',
    options: [
      'HyperText Markup Language',
      'High-level Text Machine Language',
      'Hyper Transfer Markup Language',
      'Home Tool Mark Language',
    ],
    correctIndex: 0,
    explanation: 'HTML é a linguagem de marcação da web.',
    hint: 'A primeira palavra é "HyperText".',
  },
  {
    id: 'lng-e-07',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Qual operador compara valor E tipo em JavaScript?',
    options: ['==', '===', '=', '!='],
    correctIndex: 1,
    explanation: '`===` é o operador de comparação estrita (sem coerção).',
    hint: 'Três sinais de igual.',
  },
  {
    id: 'lng-e-08',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Qual linguagem é compilada para a JVM?',
    options: ['Python', 'Go', 'Kotlin', 'Rust'],
    correctIndex: 2,
    explanation: 'Kotlin compila para bytecode da JVM (e também tem alvos Native/JS).',
    hint: 'É comum em desenvolvimento Android.',
  },
  {
    id: 'lng-e-09',
    themeId: 'languages',
    level: 'easy',
    prompt: 'Em Python, o que `len([1, 2, 3])` retorna?',
    options: ['2', '3', '[1,2,3]', 'erro'],
    correctIndex: 1,
    explanation: '`len` devolve o número de elementos da sequência.',
    hint: 'É a quantidade de itens na lista.',
  },
  {
    id: 'lng-e-10',
    themeId: 'languages',
    level: 'easy',
    prompt: 'CSS é uma linguagem usada para…',
    options: [
      'Banco de dados',
      'Estilizar páginas web',
      'Programar lógica de back-end',
      'Compilar binários',
    ],
    correctIndex: 1,
    explanation: 'CSS define a aparência (cores, layout, tipografia) de páginas web.',
    hint: 'Cascading Style Sheets.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'lng-m-01',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Em JavaScript, qual o valor de `typeof null`?',
    options: ['"null"', '"object"', '"undefined"', '"number"'],
    correctIndex: 1,
    explanation: 'Historicamente `typeof null` é "object" — um bug famoso preservado por compatibilidade.',
    hint: 'É um "bug histórico" da linguagem.',
  },
  {
    id: 'lng-m-02',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Em Python, qual o resultado de `3 * "ab"`?',
    options: ['"ababab"', '"3ab"', 'erro', '"ab3"'],
    correctIndex: 0,
    explanation: 'O operador * em strings repete a sequência.',
    hint: 'Strings podem ser "multiplicadas" por inteiros.',
  },
  {
    id: 'lng-m-03',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Qual conceito permite a uma função lembrar o escopo onde foi criada?',
    options: ['Closure', 'Hoisting', 'Coerção', 'Prototype'],
    correctIndex: 0,
    explanation: 'Closure captura variáveis do escopo léxico onde a função foi definida.',
    hint: 'Em inglês significa "fechamento".',
  },
  {
    id: 'lng-m-04',
    themeId: 'languages',
    level: 'medium',
    prompt: 'TypeScript: o que faz `as const` aplicado a um objeto?',
    options: [
      'Transforma em readonly e literal types',
      'Cria uma instância imutável em runtime',
      'Bloqueia o JIT',
      'Converte para JSON',
    ],
    correctIndex: 0,
    explanation: '`as const` produz tipos literais e marca campos como readonly.',
    hint: 'Pense em tipagem mais estrita, não em runtime.',
  },
  {
    id: 'lng-m-05',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Em Java, qual interface marca classes cujos objetos podem ser comparados naturalmente?',
    options: ['Comparator', 'Comparable', 'Sortable', 'Iterable'],
    correctIndex: 1,
    explanation: 'Comparable<T> define `compareTo` para ordenação natural; Comparator é externo.',
    hint: 'É implementada pela própria classe que define a ordem.',
  },
  {
    id: 'lng-m-06',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Qual destes é um "fall-through" comum em switch sem `break`?',
    options: [
      'Executa apenas o primeiro case',
      'Continua executando os cases seguintes',
      'Lança exceção',
      'Reinicia o switch',
    ],
    correctIndex: 1,
    explanation: 'Sem `break`, a execução "vaza" para os próximos cases.',
    hint: 'Daí o nome "fall-through" (cair adiante).',
  },
  {
    id: 'lng-m-07',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Em Go, como se declara função que retorna múltiplos valores?',
    options: [
      'func f() (int, error)',
      'function f(): int, error',
      'def f -> (int, error)',
      'fn f() -> (int, error)',
    ],
    correctIndex: 0,
    explanation: 'Go usa `func nome() (tipo1, tipo2)`.',
    hint: 'Pense na sintaxe característica do Go.',
  },
  {
    id: 'lng-m-08',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Em Python, o que diferencia tupla de lista?',
    options: [
      'Tupla é mutável; lista é imutável',
      'Tupla é imutável; lista é mutável',
      'Tupla só guarda números',
      'Lista usa parênteses',
    ],
    correctIndex: 1,
    explanation: 'Tuplas são imutáveis (criadas com parênteses); listas são mutáveis (colchetes).',
    hint: 'Qual delas você pode modificar depois de criar?',
  },
  {
    id: 'lng-m-09',
    themeId: 'languages',
    level: 'medium',
    prompt: 'Promises em JavaScript podem estar nos estados…',
    options: [
      'pending, fulfilled, rejected',
      'open, closed, error',
      'start, end, fail',
      'sync, async, idle',
    ],
    correctIndex: 0,
    explanation: 'Estados de uma Promise: pending → fulfilled (resolved) ou rejected.',
    hint: 'São três estados, começando por "pending".',
  },
  {
    id: 'lng-m-10',
    themeId: 'languages',
    level: 'medium',
    prompt: 'C# é principalmente associada a qual plataforma?',
    options: ['.NET', 'JVM', 'CPython', 'V8'],
    correctIndex: 0,
    explanation: 'C# roda sobre o runtime .NET (CLR).',
    hint: 'Plataforma da Microsoft.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'lng-h-01',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Qual o resultado de `0.1 + 0.2 === 0.3` em JavaScript?',
    options: ['true', 'false', 'NaN', 'erro de sintaxe'],
    correctIndex: 1,
    explanation: 'Devido à aritmética IEEE-754, `0.1+0.2` é 0.30000000000000004.',
    hint: 'A culpa é da representação binária dos floats.',
  },
  {
    id: 'lng-h-02',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em TypeScript, `keyof { a: 1; b: 2 }` resolve para…',
    options: ['"a" | "b"', '1 | 2', 'string', 'never'],
    correctIndex: 0,
    explanation: '`keyof` produz a união literal dos nomes das chaves.',
    hint: 'Pense nas chaves, não nos valores.',
  },
  {
    id: 'lng-h-03',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em Python, qual o efeito de `*args` em uma assinatura de função?',
    options: [
      'Recebe argumentos por palavra-chave',
      'Recebe argumentos posicionais variáveis como tupla',
      'Marca a função como assíncrona',
      'Define args como kwargs',
    ],
    correctIndex: 1,
    explanation: '*args coleta argumentos posicionais extras em uma tupla.',
    hint: 'É a versão "posicional"; existe **kwargs para nomeados.',
  },
  {
    id: 'lng-h-04',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Qual destes mecanismos do Rust impede data races em tempo de compilação?',
    options: ['Garbage collector', 'Ownership e Borrow checker', 'Threads verdes', 'GIL'],
    correctIndex: 1,
    explanation: 'O Borrow checker valida regras de propriedade e empréstimo no compilador.',
    hint: 'Trata de "quem é dono" da memória.',
  },
  {
    id: 'lng-h-05',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em Java, qual diferença entre `==` e `.equals()` para Strings?',
    options: [
      'Não há diferença',
      '`==` compara referências; `.equals` compara conteúdo',
      '`==` lança exceção em null',
      '.equals só funciona em listas',
    ],
    correctIndex: 1,
    explanation: 'Em Java `==` testa identidade de referência; `equals` é definido por conteúdo na classe String.',
    hint: 'Uma compara endereço de memória, outra valor.',
  },
  {
    id: 'lng-h-06',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em JavaScript, qual a saída de `[1,2,3].map(parseInt)`?',
    options: ['[1,2,3]', '[1, NaN, NaN]', '[NaN, NaN, NaN]', '["1","2","3"]'],
    correctIndex: 1,
    explanation: 'parseInt recebe (valor, radix); o índice 0, 1, 2 vira a base, gerando NaN em bases inválidas.',
    hint: 'Cuidado com os argumentos extras que map fornece.',
  },
  {
    id: 'lng-h-07',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em C, o que diferencia `int *p, q;` quanto à declaração?',
    options: [
      'p e q são ambos ponteiros',
      'p é ponteiro, q é int',
      'q é ponteiro, p é int',
      'Erro de compilação',
    ],
    correctIndex: 1,
    explanation: 'O asterisco se aplica apenas ao identificador mais próximo.',
    hint: 'O `*` está colado em p, não em q.',
  },
  {
    id: 'lng-h-08',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em Python, o que `yield` transforma a função em?',
    options: ['Decorador', 'Gerador', 'Coroutine completa', 'Lambda'],
    correctIndex: 1,
    explanation: 'Funções com `yield` retornam um gerador (objeto iterável preguiçoso).',
    hint: 'Produz valores um a um, sob demanda.',
  },
  {
    id: 'lng-h-09',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em JS, `for...in` itera sobre…',
    options: [
      'Valores de um iterável',
      'Chaves enumeráveis de um objeto',
      'Apenas arrays',
      'Promises pendentes',
    ],
    correctIndex: 1,
    explanation: '`for...in` percorre chaves enumeráveis; `for...of` percorre valores de iteráveis.',
    hint: 'Cuidado: não confunda com for...of.',
  },
  {
    id: 'lng-h-10',
    themeId: 'languages',
    level: 'hard',
    prompt: 'Em Kotlin, qual modificador permite estender uma classe?',
    options: ['final', 'open', 'sealed', 'data'],
    correctIndex: 1,
    explanation: 'Classes em Kotlin são `final` por padrão; `open` permite herança.',
    hint: 'É o oposto de "final".',
  },
] as const;
