import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const LOGIC_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'log-e-01',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Qual é o resultado de `true AND false`?',
    options: ['true', 'false', 'null', 'undefined'],
    correctIndex: 1,
    explanation: 'AND só é verdadeiro quando ambos operandos são verdadeiros.',
    hint: 'AND exige que todos sejam verdadeiros.',
  },
  {
    id: 'log-e-02',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Qual é o próximo número na sequência: 2, 4, 6, 8, …?',
    options: ['9', '10', '12', '7'],
    correctIndex: 1,
    explanation: 'Adição constante de 2.',
    hint: 'Note o passo entre os números.',
  },
  {
    id: 'log-e-03',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Qual é a negação lógica de "está chovendo"?',
    options: [
      '"vai chover"',
      '"não está chovendo"',
      '"talvez chova"',
      '"choverá amanhã"',
    ],
    correctIndex: 1,
    explanation: 'A negação simples inverte a afirmação.',
    hint: 'Apenas inverta o sentido.',
  },
  {
    id: 'log-e-04',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Qual é o resultado de `NOT true`?',
    options: ['true', 'false', 'erro', 'NaN'],
    correctIndex: 1,
    explanation: 'NOT inverte o valor lógico.',
    hint: 'É a inversão.',
  },
  {
    id: 'log-e-05',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Quantos resultados possíveis há ao lançar uma moeda?',
    options: ['1', '2', '3', '4'],
    correctIndex: 1,
    explanation: 'Cara ou coroa.',
    hint: 'Pense nas duas faces.',
  },
  {
    id: 'log-e-06',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Em uma proposição "se A então B", se A é falso, B é necessariamente:',
    options: ['Verdadeiro', 'Falso', 'A implicação ainda é verdadeira', 'Inválido'],
    correctIndex: 2,
    explanation: 'Implicação só é falsa quando A é V e B é F. Com A falso, a implicação é verdadeira.',
    hint: 'Pense na tabela-verdade da implicação.',
  },
  {
    id: 'log-e-07',
    themeId: 'logic',
    level: 'easy',
    prompt: 'O símbolo ∨ representa qual operador?',
    options: ['AND', 'OR', 'XOR', 'NOT'],
    correctIndex: 1,
    explanation: '∨ é a disjunção lógica (OR).',
    hint: 'Lembra o "v" de "or" em inglês.',
  },
  {
    id: 'log-e-08',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Qual o complemento de um conjunto vazio dentro de um universo U?',
    options: ['Vazio', 'U', 'Próprio elemento', 'Indefinido'],
    correctIndex: 1,
    explanation: 'O complemento do vazio é o universo todo.',
    hint: 'Se ninguém está fora, todos estão dentro.',
  },
  {
    id: 'log-e-09',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Quantos bits cabem em 1 byte?',
    options: ['4', '8', '16', '32'],
    correctIndex: 1,
    explanation: '1 byte = 8 bits.',
    hint: 'É a base do "octeto".',
  },
  {
    id: 'log-e-10',
    themeId: 'logic',
    level: 'easy',
    prompt: 'Se a proposição é "Todo A é B" e "Pedro é A", então:',
    options: [
      'Pedro pode ou não ser B',
      'Pedro é B',
      'Pedro não é B',
      'Faltam dados',
    ],
    correctIndex: 1,
    explanation: 'Silogismo clássico de Aristóteles.',
    hint: 'É um silogismo direto.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'log-m-01',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Quantas operações faz um algoritmo de busca linear no pior caso para n elementos?',
    options: ['log n', 'n', 'n log n', 'n²'],
    correctIndex: 1,
    explanation: 'Busca linear pode percorrer todos os n elementos.',
    hint: 'Tempo proporcional ao tamanho da lista.',
  },
  {
    id: 'log-m-02',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Quantos resultados possíveis há ao lançar dois dados de 6 lados?',
    options: ['6', '12', '36', '11'],
    correctIndex: 2,
    explanation: '6 × 6 = 36 pares ordenados.',
    hint: 'Multiplique as possibilidades.',
  },
  {
    id: 'log-m-03',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Qual a próxima da sequência: 1, 1, 2, 3, 5, 8, …?',
    options: ['11', '12', '13', '14'],
    correctIndex: 2,
    explanation: 'Fibonacci: cada termo é a soma dos dois anteriores.',
    hint: '5 + 8 = ?',
  },
  {
    id: 'log-m-04',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Em XOR, quando o resultado é verdadeiro?',
    options: [
      'Ambos verdadeiros',
      'Exatamente um verdadeiro',
      'Ambos falsos',
      'Nunca',
    ],
    correctIndex: 1,
    explanation: 'XOR (ou exclusivo) é verdadeiro quando há paridade ímpar de verdadeiros.',
    hint: 'XOR exclui o caso em que ambos são verdadeiros.',
  },
  {
    id: 'log-m-05',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Quantos subconjuntos tem um conjunto de 4 elementos?',
    options: ['8', '15', '16', '24'],
    correctIndex: 2,
    explanation: '2^n = 2^4 = 16, incluindo o vazio e o total.',
    hint: 'Dobre para cada elemento (potência de 2).',
  },
  {
    id: 'log-m-06',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Se p → q e q → r, então logicamente:',
    options: ['p → r', 'r → p', 'p ∨ r', 'p ∧ ¬r'],
    correctIndex: 0,
    explanation: 'Transitividade da implicação.',
    hint: 'Implicações em cadeia se "conectam".',
  },
  {
    id: 'log-m-07',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Qual algoritmo é base do "dividir para conquistar"?',
    options: ['Bubble sort', 'Merge sort', 'Selection sort', 'Counting sort'],
    correctIndex: 1,
    explanation: 'Merge sort divide pela metade até listas unitárias e mescla ordenando.',
    hint: 'Começa por "Merge".',
  },
  {
    id: 'log-m-08',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Quantas torres mínimas precisam ser movidas em Torre de Hanói com 3 discos?',
    options: ['3', '5', '7', '9'],
    correctIndex: 2,
    explanation: '2^n - 1 = 2^3 - 1 = 7 movimentos.',
    hint: 'É a fórmula 2^n − 1.',
  },
  {
    id: 'log-m-09',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Recursão é uma técnica em que…',
    options: [
      'Loop incrementa contador',
      'Função chama a si mesma',
      'Compilador otimiza GOTO',
      'Memória é alocada estaticamente',
    ],
    correctIndex: 1,
    explanation: 'Recursão = função que chama a si mesma com problema menor.',
    hint: 'A palavra deriva de "recurrente".',
  },
  {
    id: 'log-m-10',
    themeId: 'logic',
    level: 'medium',
    prompt: 'Qual a complexidade média da busca binária?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    correctIndex: 1,
    explanation: 'Cada passo descarta metade dos elementos.',
    hint: 'Aparece "log" porque a entrada é cortada pela metade.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'log-h-01',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Qual a complexidade do quicksort no pior caso?',
    options: ['O(log n)', 'O(n log n)', 'O(n²)', 'O(n)'],
    correctIndex: 2,
    explanation: 'Pior caso ocorre quando o pivô é mal escolhido (ex.: já ordenado).',
    hint: 'A média é boa, mas o pior caso degrada.',
  },
  {
    id: 'log-h-02',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Em lógica proposicional, contrapositiva de "p → q" é:',
    options: ['¬q → ¬p', 'q → p', '¬p → q', 'p ∧ q'],
    correctIndex: 0,
    explanation: 'Contrapositiva preserva o valor lógico da implicação.',
    hint: 'Negue e inverta a ordem.',
  },
  {
    id: 'log-h-03',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Quantas permutações distintas tem a palavra "BANANA"?',
    options: ['60', '120', '720', '6'],
    correctIndex: 0,
    explanation: '6!/(3!·2!) = 720 / 12 = 60.',
    hint: 'Há letras repetidas: divida pelas repetições.',
  },
  {
    id: 'log-h-04',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Lei de De Morgan: ¬(A ∧ B) é equivalente a:',
    options: ['¬A ∧ ¬B', '¬A ∨ ¬B', 'A ∨ B', '¬A → ¬B'],
    correctIndex: 1,
    explanation: 'Negar uma conjunção dá disjunção das negações.',
    hint: 'Vira "ou" com cada termo negado.',
  },
  {
    id: 'log-h-05',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Qual a base do raciocínio por indução matemática?',
    options: [
      'Caso base e passo indutivo',
      'Contraexemplo',
      'Refutação',
      'Negação',
    ],
    correctIndex: 0,
    explanation: 'Prova-se P(0) e P(n) → P(n+1).',
    hint: 'São dois passos: um inicial e outro recorrente.',
  },
  {
    id: 'log-h-06',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Um algoritmo guloso (greedy) sempre garante solução ótima?',
    options: ['Sim', 'Não', 'Apenas em grafos', 'Apenas em listas'],
    correctIndex: 1,
    explanation: 'Greedy garante ótimo apenas em problemas com estrutura ótima local + global compatível.',
    hint: 'Pense em troco com moedas de valores arbitrários.',
  },
  {
    id: 'log-h-07',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Em programação dinâmica, a propriedade essencial é:',
    options: [
      'Estado independente do anterior',
      'Subestrutura ótima e sobreposição de subproblemas',
      'Apenas problemas em grafos',
      'Falta de memória',
    ],
    correctIndex: 1,
    explanation: 'PD se beneficia de memoização e estrutura ótima nas partes.',
    hint: 'Subproblemas se repetem; vale guardar.',
  },
  {
    id: 'log-h-08',
    themeId: 'logic',
    level: 'hard',
    prompt: 'O problema da parada é:',
    options: [
      'Polinomial',
      'NP-completo',
      'Indecidível',
      'Resolúvel em O(n)',
    ],
    correctIndex: 2,
    explanation: 'Turing mostrou que não existe algoritmo geral que decida se um programa para.',
    hint: 'Turing demonstrou impossibilidade.',
  },
  {
    id: 'log-h-09',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Qual a complexidade espacial típica de BFS em grafos?',
    options: ['O(1)', 'O(log V)', 'O(V)', 'O(V²)'],
    correctIndex: 2,
    explanation: 'BFS usa fila que pode armazenar todos os vértices visitados.',
    hint: 'Pense em quantos elementos na fila.',
  },
  {
    id: 'log-h-10',
    themeId: 'logic',
    level: 'hard',
    prompt: 'Em teoria dos conjuntos, |P(A)| (cardinalidade do conjunto das partes) é:',
    options: ['|A|', '2|A|', '2^|A|', '|A|²'],
    correctIndex: 2,
    explanation: 'Para cada elemento, dois resultados (entrar ou não).',
    hint: 'Cada elemento entra ou não — multiplicação por 2.',
  },
] as const;
