import type { QuizQuestion } from '@/lib/quiz/questions/types';

export const NETWORKS_QUESTIONS: readonly QuizQuestion[] = [
  // ------------------------- FÁCIL -------------------------
  {
    id: 'net-e-01',
    themeId: 'networks',
    level: 'easy',
    prompt: 'O que significa HTTP?',
    options: [
      'Hyper Text Transfer Protocol',
      'High Tech Transmission Protocol',
      'Home Transfer Text Procedure',
      'Hyper Tool Transport Plan',
    ],
    correctIndex: 0,
    explanation: 'HTTP é o protocolo de aplicação da web.',
    hint: 'Começa com "Hyper Text".',
  },
  {
    id: 'net-e-02',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Qual porta padrão do HTTPS?',
    options: ['80', '443', '21', '22'],
    correctIndex: 1,
    explanation: '443 é a porta padrão do HTTPS; 80 do HTTP.',
    hint: 'Acima de 400.',
  },
  {
    id: 'net-e-03',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Qual destes é um endereço IPv4 válido?',
    options: ['192.168.0.1', '256.0.0.1', '192.168.0', 'gg.hh.ii.jj'],
    correctIndex: 0,
    explanation: 'IPv4 são 4 octetos de 0 a 255.',
    hint: 'Cada parte vai até 255.',
  },
  {
    id: 'net-e-04',
    themeId: 'networks',
    level: 'easy',
    prompt: 'DNS serve para:',
    options: [
      'Cifrar tráfego',
      'Resolver nomes em endereços IP',
      'Comprimir arquivos',
      'Roteamento físico',
    ],
    correctIndex: 1,
    explanation: 'DNS traduz nomes (google.com) em IPs.',
    hint: 'Pense em "agenda de contatos da internet".',
  },
  {
    id: 'net-e-05',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Qual desses é um método HTTP?',
    options: ['GET', 'SCAN', 'LOAD', 'OPEN'],
    correctIndex: 0,
    explanation: 'GET, POST, PUT, DELETE, PATCH são métodos HTTP comuns.',
    hint: 'É o mais comum, usado para "ler".',
  },
  {
    id: 'net-e-06',
    themeId: 'networks',
    level: 'easy',
    prompt: 'O status HTTP 404 significa:',
    options: ['Sucesso', 'Não encontrado', 'Erro do servidor', 'Não autorizado'],
    correctIndex: 1,
    explanation: '4xx = erro do cliente; 404 = recurso ausente.',
    hint: 'É o famoso "página não encontrada".',
  },
  {
    id: 'net-e-07',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Cabo Ethernet usa o conector:',
    options: ['USB-C', 'RJ45', 'BNC', 'HDMI'],
    correctIndex: 1,
    explanation: 'RJ45 é o conector clássico de cabos Ethernet.',
    hint: 'Começa com "RJ".',
  },
  {
    id: 'net-e-08',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Qual destes é um protocolo de transporte?',
    options: ['IP', 'TCP', 'HTTP', 'DNS'],
    correctIndex: 1,
    explanation: 'TCP e UDP atuam na camada de transporte.',
    hint: 'É confiável e orientado a conexão.',
  },
  {
    id: 'net-e-09',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Em URLs, qual a parte conhecida como "esquema"?',
    options: ['https://', '/path', '?query', '#hash'],
    correctIndex: 0,
    explanation: 'O esquema (scheme) define o protocolo.',
    hint: 'Vem antes do "://".',
  },
  {
    id: 'net-e-10',
    themeId: 'networks',
    level: 'easy',
    prompt: 'Que serviço dinamiza atribuição de IPs em uma rede?',
    options: ['DHCP', 'DNS', 'NAT', 'ARP'],
    correctIndex: 0,
    explanation: 'DHCP entrega IPs e configurações automaticamente.',
    hint: 'Distribui endereços automaticamente.',
  },

  // ------------------------- MÉDIO -------------------------
  {
    id: 'net-m-01',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Qual a diferença essencial entre TCP e UDP?',
    options: [
      'TCP é mais rápido sempre',
      'TCP é confiável e orientado à conexão; UDP é não confiável e sem conexão',
      'UDP suporta TLS, TCP não',
      'TCP só funciona em IPv6',
    ],
    correctIndex: 1,
    explanation: 'TCP fornece entrega ordenada/confiável; UDP é leve, sem garantias.',
    hint: 'Um garante entrega, outro não.',
  },
  {
    id: 'net-m-02',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Em HTTP, "stateless" significa:',
    options: [
      'Não usa sockets',
      'Cada requisição é independente do estado anterior',
      'Não pode usar cookies',
      'Não permite TLS',
    ],
    correctIndex: 1,
    explanation: 'O servidor HTTP não precisa lembrar de requisições anteriores nativamente.',
    hint: 'O nome traz "sem estado".',
  },
  {
    id: 'net-m-03',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Status 401 vs 403:',
    options: [
      '401 = não autorizado (sem auth); 403 = autenticado mas sem permissão',
      'São equivalentes',
      '401 = não encontrado; 403 = erro de servidor',
      '401 = erro de cliente; 403 = sucesso',
    ],
    correctIndex: 0,
    explanation: '401 indica falta de autenticação; 403 indica autenticado sem direito.',
    hint: 'Um é "quem é você?", outro é "você não pode".',
  },
  {
    id: 'net-m-04',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Qual a função do "TLS handshake"?',
    options: [
      'Trocar chaves e estabelecer canal cifrado',
      'Comprimir requisições',
      'Realizar roteamento',
      'Resolver DNS',
    ],
    correctIndex: 0,
    explanation: 'O handshake negocia algoritmos, autentica e estabelece sessão segura.',
    hint: 'Tem a ver com criptografia segura.',
  },
  {
    id: 'net-m-05',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Qual camada do modelo OSI o IP pertence?',
    options: ['Enlace', 'Rede', 'Transporte', 'Aplicação'],
    correctIndex: 1,
    explanation: 'IP é da camada 3 (rede).',
    hint: 'Camada do roteamento.',
  },
  {
    id: 'net-m-06',
    themeId: 'networks',
    level: 'medium',
    prompt: 'O que faz o NAT?',
    options: [
      'Cifra pacotes IP',
      'Traduz endereços privados em públicos e vice-versa',
      'Decide rotas dinâmicas',
      'Resolve nomes DNS',
    ],
    correctIndex: 1,
    explanation: 'Network Address Translation permite que várias máquinas privadas compartilhem um IP público.',
    hint: 'Tradução de endereços.',
  },
  {
    id: 'net-m-07',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Qual a função do cabeçalho HTTP `Cache-Control`?',
    options: [
      'Cifrar a resposta',
      'Definir políticas de cache de respostas',
      'Habilitar CORS',
      'Indicar autenticação',
    ],
    correctIndex: 1,
    explanation: 'Controla TTLs, públicas/privadas, no-store, etc.',
    hint: 'Tem a ver com guardar respostas.',
  },
  {
    id: 'net-m-08',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Qual cabeçalho HTTP é central no CORS?',
    options: [
      'Authorization',
      'Access-Control-Allow-Origin',
      'Cookie',
      'User-Agent',
    ],
    correctIndex: 1,
    explanation: 'Define quais origens podem acessar o recurso via navegador.',
    hint: 'Tem a palavra "Origin" no nome.',
  },
  {
    id: 'net-m-09',
    themeId: 'networks',
    level: 'medium',
    prompt: 'Que faz uma CDN?',
    options: [
      'Replica conteúdo geograficamente próximo ao usuário',
      'Cifra conexões',
      'Resolve nomes em IPs',
      'Substitui o backend',
    ],
    correctIndex: 0,
    explanation: 'Content Delivery Network entrega conteúdo de servidores de borda.',
    hint: 'Distribui conteúdo perto do usuário.',
  },
  {
    id: 'net-m-10',
    themeId: 'networks',
    level: 'medium',
    prompt: 'IPv6 endereços têm:',
    options: ['32 bits', '64 bits', '128 bits', '256 bits'],
    correctIndex: 2,
    explanation: 'IPv6 usa 128 bits, expandindo o espaço de endereços.',
    hint: 'Muito maior que os 32 bits do IPv4.',
  },

  // ------------------------- DIFÍCIL -------------------------
  {
    id: 'net-h-01',
    themeId: 'networks',
    level: 'hard',
    prompt: 'HTTP/2 introduziu, dentre outros:',
    options: [
      'Texto plano em vez de binário',
      'Multiplexação de streams sobre uma conexão',
      'Eliminação de TLS',
      'Substituição do TCP',
    ],
    correctIndex: 1,
    explanation: 'HTTP/2 multiplexa múltiplas requisições em uma única conexão TCP.',
    hint: 'Solucionou o "head-of-line blocking" do HTTP/1.1 parcialmente.',
  },
  {
    id: 'net-h-02',
    themeId: 'networks',
    level: 'hard',
    prompt: 'QUIC roda sobre:',
    options: ['TCP', 'UDP', 'IP diretamente', 'TLS sem transporte'],
    correctIndex: 1,
    explanation: 'QUIC é construído sobre UDP, com criptografia e multiplexação.',
    hint: 'Foi escolhido para evitar a inércia do TCP.',
  },
  {
    id: 'net-h-03',
    themeId: 'networks',
    level: 'hard',
    prompt: 'Em TLS 1.3, o número de RTTs do handshake completo é:',
    options: ['0', '1', '2', '3'],
    correctIndex: 1,
    explanation: 'TLS 1.3 reduz para 1-RTT (e 0-RTT com PSK).',
    hint: 'Foi reduzido em relação ao TLS 1.2.',
  },
  {
    id: 'net-h-04',
    themeId: 'networks',
    level: 'hard',
    prompt: 'BGP é um protocolo de:',
    options: [
      'Roteamento interno (IGP)',
      'Roteamento entre sistemas autônomos (EGP)',
      'Resolução de nomes',
      'Multicast',
    ],
    correctIndex: 1,
    explanation: 'Border Gateway Protocol roteia entre Autonomous Systems da internet.',
    hint: 'Atua nas "bordas" da internet.',
  },
  {
    id: 'net-h-05',
    themeId: 'networks',
    level: 'hard',
    prompt: 'O que ARP resolve?',
    options: [
      'IP em MAC',
      'MAC em IP',
      'Nome em IP',
      'IP em rota',
    ],
    correctIndex: 0,
    explanation: 'ARP descobre o MAC associado a um IP na mesma rede.',
    hint: 'Mapeia endereço lógico em endereço físico.',
  },
  {
    id: 'net-h-06',
    themeId: 'networks',
    level: 'hard',
    prompt: 'Em HTTP, o status 451 representa:',
    options: [
      'Erro de gateway',
      'Indisponível por questões legais',
      'Conflito',
      'Limite de taxa',
    ],
    correctIndex: 1,
    explanation: '451 é "Unavailable For Legal Reasons" (alusão a Fahrenheit 451).',
    hint: 'Referência literária famosa.',
  },
  {
    id: 'net-h-07',
    themeId: 'networks',
    level: 'hard',
    prompt: 'TCP slow start é um mecanismo de:',
    options: [
      'Congestion control',
      'Flow control',
      'Reordenamento',
      'Multiplexação',
    ],
    correctIndex: 0,
    explanation: 'Slow start aumenta a janela de congestionamento exponencialmente até o threshold.',
    hint: 'Trata de evitar saturar a rede.',
  },
  {
    id: 'net-h-08',
    themeId: 'networks',
    level: 'hard',
    prompt: 'Diferença entre cookie com `HttpOnly` e sem:',
    options: [
      'Apenas em https',
      'Não acessível por JavaScript',
      'Compactação automática',
      'Validade infinita',
    ],
    correctIndex: 1,
    explanation: 'HttpOnly impede acesso via document.cookie, mitigando XSS.',
    hint: 'Aumenta segurança contra XSS.',
  },
  {
    id: 'net-h-09',
    themeId: 'networks',
    level: 'hard',
    prompt: 'WebSocket começa via:',
    options: [
      'HTTP Upgrade',
      'DNS query',
      'TCP fast open',
      'gRPC',
    ],
    correctIndex: 0,
    explanation: 'O cliente faz um HTTP GET com Upgrade: websocket.',
    hint: 'O handshake inicial é HTTP.',
  },
  {
    id: 'net-h-10',
    themeId: 'networks',
    level: 'hard',
    prompt: 'O que faz HSTS?',
    options: [
      'Força navegador a usar HTTPS para um domínio',
      'Cria backup do DNS',
      'Cifra cookies',
      'Substitui TLS',
    ],
    correctIndex: 0,
    explanation: 'HTTP Strict Transport Security informa ao navegador para nunca usar HTTP simples no domínio.',
    hint: 'A sigla começa por "HTTP Strict Transport".',
  },
] as const;
